------------------------

GET ALL Accounts

GET localhost:5000/api/accounts/
Authorization: // Insert Bearer Token
Content-type: application/json

------------------------

GET Accounts

GET localhost:5000/api/accounts/:type
Authorization: // Insert Bearer Token
Content-type: application/json

------------------------

GET One Account

GET localhost:5000/api/accounts/get/:id
Authorization: // Insert Bearer Token
Content-type: application/json

------------------------

GET Queue Window Accounts

GET localhost:5000/api/accounts/windows/:queueName
Authorization: // Insert Bearer Token
Content-type: application/json

------------------------

GET Queue Flashboard Accounts

GET localhost:5000/api/accounts/flashboards/:queueName
Authorization: // Insert Bearer Token
Content-type: application/json

------------------------

CREATE Flashboards Accounts

PUT localhost:5000/api/accounts/flashboards-create/:queueName
Authorization: // Insert Bearer Token
Content-type: application/json

------------------------

CREATE Window Accounts

PUT localhost:5000/api/accounts/windows-create/:queueName
Authorization: // Insert Bearer Token
Content-type: application/json

------------------------

UPDATE Accounts

PUT localhost: 5000/api/accounts/update/:adminId
Authorization: // Insert Bearer Token
Content-type: application/json

------------------------

Delete Accounts

PUT localhost: 5000/api/accounts/delete/:adminId
Authorization: // Insert Bearer Token
Content-type: application/json





