------------------------

Admin Login Route

POST localhost:5000/api/auth/login
Content-type: application/json
Body: {
    "username" : "ArchonSA",
    "password" : "queue123"
}
// This account is a Super Admin Account

------------------------

Admin Create

POST localhost:5000/api/auth/create
Content-type: application/json
Body: {
    adminType: 'Super',
    fullName: {
        firstName: '',
        middleName: '',
        lastName: '',
        nameExtension: ''
    },
    address: '',
    contact: {
        email: ''
    },
    permissions: []
}

-------------------------

Email Send

POST localhost:5000/api/auth/send-email
Content-type: application/json
Authorization 